
export const data = [
    {
        title: 'Eccomerce App',
        img: [
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610405/Portafolio/English/Eccomerce%20app/1_zqsjjw.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610405/Portafolio/English/Eccomerce%20app/2_m5uqvz.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610405/Portafolio/English/Eccomerce%20app/3_hzbmfs.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610406/Portafolio/English/Eccomerce%20app/5_xhdp7k.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610406/Portafolio/English/Eccomerce%20app/6_ryal22.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610406/Portafolio/English/Eccomerce%20app/7_vc95z2.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610406/Portafolio/English/Eccomerce%20app/8_awwguz.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610406/Portafolio/English/Eccomerce%20app/9_rpdaxv.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610405/Portafolio/English/Eccomerce%20app/4_kkqrd6.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610406/Portafolio/English/Eccomerce%20app/10_nzw8ab.jpg',
        ],
        description: {
            items: [
                'Sales app.',
                'Project done on my own both front-end and back-end.',
                'Responsive design.',
                'For more details go to the github repository.',
            ]
        },
        tecnologias: {
            html: true,
            css: true,
            sass: false,
            react: true,
            javascript: true,
            node: true,
            express: true,
            mongoDb: true,
        },
        github: "https://github.com/lucasgojeda/eccomerce-app-frontend-vite",
        demo: "https://my-ecommerce-app-vite.netlify.app/",
    },
    {
        title: 'Dashboard App',
        img: [
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610383/Portafolio/English/Dashboard%20app/1_hkxrmb.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610383/Portafolio/English/Dashboard%20app/2_r9frnm.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610383/Portafolio/English/Dashboard%20app/3_vah90n.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610383/Portafolio/English/Dashboard%20app/4_rbgibt.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610383/Portafolio/English/Dashboard%20app/5_ebdrjg.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610383/Portafolio/English/Dashboard%20app/6_jng2bg.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610383/Portafolio/English/Dashboard%20app/7_dudigl.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610383/Portafolio/English/Dashboard%20app/8_wawhsp.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610383/Portafolio/English/Dashboard%20app/9_y4trub.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610383/Portafolio/English/Dashboard%20app/10_a1kdbx.jpg',
        ],
        description: {
            items: [
                'Dashboard of an ecommerce project.',
                'Project done on my own both front-end and back-end.',
                'Two roles allowed: Moderator and Administrator.',
                'It has a registration system.',
                'Responsive design.',
                'For more details go to the github repository.',
            ]
        },
        tecnologias: {
            html: true,
            css: true,
            sass: false,
            react: true,
            javascript: true,
            node: true,
            express: true,
            mongoDb: true,
        },
        github: "https://github.com/lucasgojeda/eccomerce-app-dashboard",
        demo: "https://my-eccomerce-dashboard.netlify.app/",
    },
    {
        
        title: 'Alkybank (Alkemy)',
        img: [
            'https://res.cloudinary.com/the-kings-company/image/upload/v1673229902/Portafolio/English/Alkybank%20app/1_ir4egw.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1673229902/Portafolio/English/Alkybank%20app/2_mvkhuj.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1673229902/Portafolio/English/Alkybank%20app/3_ypawyg.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1673229902/Portafolio/English/Alkybank%20app/4_hirtsw.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1673229902/Portafolio/English/Alkybank%20app/5_qott15.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1673229902/Portafolio/English/Alkybank%20app/6_cpfylo.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1673229903/Portafolio/English/Alkybank%20app/7_z6iqmd.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1673229903/Portafolio/English/Alkybank%20app/8_ehbbkl.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1673229904/Portafolio/English/Alkybank%20app/9_zk7imz.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1673229904/Portafolio/English/Alkybank%20app/10_nmpf5e.jpg',
        ],
        description: {
            items: [
                'Virtual wallet for a bank.',
                'Project made during the alkemy acceleration.',
                'Carried out as a team using agile methodologies.',
                'Responsive design.',
                'For more details go to the github repository.',
            ]
        },
        tecnologias: {
            html: true,
            css: true,
            sass: false,
            react: true,
            javascript: true,
            node: false,
            express: false,
            mongoDb: false,
        },
        github: "https://github.com/SkillUp-Grupo5/SKU-5",
        demo: "https://alkybank-wallet.netlify.app/",
    },
    {
        title: 'Calendar App',
        img: [
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610364/Portafolio/English/Calendar%20app/1_woahmp.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610364/Portafolio/English/Calendar%20app/2_dk2onk.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610364/Portafolio/English/Calendar%20app/3_xrnqc8.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610364/Portafolio/English/Calendar%20app/4_vcqupx.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610364/Portafolio/English/Calendar%20app/5_ckaxg6.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610364/Portafolio/English/Calendar%20app/6_htfrpp.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610364/Portafolio/English/Calendar%20app/7_xuawt1.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610364/Portafolio/English/Calendar%20app/8_gjitji.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610364/Portafolio/English/Calendar%20app/9_ro1u0k.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610364/Portafolio/English/Calendar%20app/10_dwxlw6.jpg',
        ],
        description: {
            items: [
                'Calendar application to schedule appointments.',
                'Project carried out in the course of Fernando Herrera.',
                'Includes unit tests.',
                'Responsive design.',
                'For more details go to the github repository.',
            ]
        },
        tecnologias: {
            html: true,
            css: true,
            sass: false,
            react: true,
            javascript: true,
            node: true,
            express: true,
            mongoDb: true,
        },
        github: "https://github.com/lucasgojeda/front-calendar-app-vite",
        demo: "https://my-calendar-app-vite.netlify.app/",
    },
    {
        title: 'Journal App',
        img: [
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661976642/Portafolio/JournalApp/2_f2qdlp.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661976642/Portafolio/JournalApp/3_oipal5.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661976642/Portafolio/JournalApp/4_n7j2ky.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661976642/Portafolio/JournalApp/5_mlm8gp.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661976642/Portafolio/JournalApp/1_hxvqfl.jpg',
        ],
        description: {
            items: [
                'Notes app.',
                'Project carried out in the course of Fernando Herrera.',
                'Includes unit tests.',
                'For more details go to the github repository.',
            ]
        },
        tecnologias: {
            html: true,
            css: true,
            sass: false,
            react: true,
            javascript: true,
            node: false,
            express: false,
            mongoDb: false,
        },
        github: "https://github.com/lucasgojeda/journal-app-vite",
        demo: "https://my-journal-app-vite.netlify.app/",
    },
    {
        title: 'Heroes App',
        img: [
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610421/Portafolio/English/Heroes%20app/1_vogycp.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610422/Portafolio/English/Heroes%20app/2_vy03aq.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610422/Portafolio/English/Heroes%20app/3_ntgzsj.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610422/Portafolio/English/Heroes%20app/4_d8m9yt.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610422/Portafolio/English/Heroes%20app/5_egubsl.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610422/Portafolio/English/Heroes%20app/6_xjtlbh.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610422/Portafolio/English/Heroes%20app/7_hfyem6.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610423/Portafolio/English/Heroes%20app/8_plvvte.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610422/Portafolio/English/Heroes%20app/9_hgaewe.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1672610422/Portafolio/English/Heroes%20app/10_u5jbho.jpg',
        ],
        description: {
            items: [
                'In it we find information and images of the heroes.',
                'Project carried out in the course of Fernando Herrera.',
                'Includes unit tests.',
                'For more details go to the github repository.',
            ]
        },
        tecnologias: {
            html: true,
            css: true,
            sass: false,
            react: true,
            javascript: true,
            node: false,
            express: false,
            mongoDb: false,
        },
        github: "https://github.com/lucasgojeda/heroes-app-vite",
        demo: "https://my-heroes-app.netlify.app/",
    },
    {
        title: 'Gif Expert App',
        img: [
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661975717/Portafolio/GifExpertApp/1_t7fyyw.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661975717/Portafolio/GifExpertApp/2_ym4o47.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661976307/Portafolio/GifExpertApp/5_rksyqb.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661975717/Portafolio/GifExpertApp/5_cf0rax.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661975717/Portafolio/GifExpertApp/4_vd6nqf.jpg',
        ],
        description: {
            items: [
                'Gif search engine consumed from a public API.',
                'Project carried out in the course of Fernando Herrera.',
                'Includes unit tests.',
                'For more details go to the github repository.',
            ]
        },
        tecnologias: {
            html: true,
            css: true,
            sass: false,
            react: true,
            javascript: true,
            node: false,
            express: false,
            mongoDb: false,
        },
        github: "https://github.com/lucasgojeda/git-expert-app-vite",
        demo: "https://my-gif-expert-app.netlify.app/",
    },
]